### ISSUE TITLE
Handling RPC request failed

### ISSUE THREAD

**Issue by dimitrisTim** [patrickjane/hss-skill#2]
First of all, very nice work on the hss framework!
I tried to make a dummy skill but get the following error in hss-sever:

> ERROR:hss_skill.rpc: Handling RPC request failed (handle() takes 6 positional arguments but 7 were given)

My skill's code is pretty simple, actually the same as in the example given in the doc:
```
from hss_skill import hss

class MoodSkill(hss.BaseSkill):
    def __init__(self):
        super().__init__()   # important, call super's constructor

    async def handle(self, request, session_id, site_id, intent_name, slots):
        return self.answer(session_id, site_id, "Thanks, I am fine")
```
Am I missing something or is it a bug?
Edit: after some investigation, I believe the problem is the `mapped_slots` parameter, which I do not provide. The abstract method `handle` of the hss.py file contains this parameter. Is the example false and needs to include this parameter?

**Comment by patrickjane** [comment]
I think the example on the very bottom is outdated; it does not reflect the changes made to support multi-language slots. However in the upper part of the documentation it says:

"When developing skills, a subclass of BaseSkill must implement the coroutine:
async def handle(request, session_id, site_id, intent_name, slots, mapped_slots)"

So yes, adding `mapped_slots` as last parameter should solve the issue. Please refer to chapter **Multiple languages support** for an explanation of `mapped_slots` vs.  `slots`.

[edit] I have updated the readme accordingly.

**Comment by dimitrisTim** [comment]
Nice, thank you very much. I will probably develop some more skills in the near future , so I might open an issue again here and there, if needed :)
